//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VdkK22CNT3Lesson11Db2210900032.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VdkCategory
    {
        public int VdkID { get; set; }
        public string VdkCateName { get; set; }
        public Nullable<bool> VdkStatus { get; set; }
    }
}
