//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VdkK22CNT3Lesson11Db2210900032.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VdkProduct
    {
        public int VdkId2210900032 { get; set; }
        public string VdkProName { get; set; }
        public Nullable<int> VdkQty { get; set; }
        public Nullable<double> VdkPrice { get; set; }
        public Nullable<int> VdkCateId { get; set; }
        public Nullable<bool> VdkActive { get; set; }
    }
}
