//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VdkK22CNT3Lesson10Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VdkAccount
    {
        public int VdkID { get; set; }
        public string VdkUserName { get; set; }
        public string VdkPassword { get; set; }
        public string VdkFullName { get; set; }
        public string VdkEmail { get; set; }
        public string VdkPhone { get; set; }
        public Nullable<bool> VdkActive { get; set; }
    }
}
