//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VdkK22CNT3Lesson10Db.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VdkK22CNT3Lesoon10DBEntities : DbContext
    {
        public VdkK22CNT3Lesoon10DBEntities()
            : base("name=VdkK22CNT3Lesoon10DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VdkAccount> VdkAccount { get; set; }
    }
}
