//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucKhoaK22CNT3Lesson12.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VuDucKhoaa_2210900032Entities : DbContext
    {
        public VuDucKhoaa_2210900032Entities()
            : base("name=VuDucKhoaa_2210900032Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Vdk_SACH> Vdk_SACH { get; set; }
        public virtual DbSet<Vdk_TACGIA> Vdk_TACGIA { get; set; }
    }
}
