//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucKhoaK22CNT3Lesson12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vdk_TACGIA
    {
        public string Vdk_MaTG { get; set; }
        public string Vdk_TenTG { get; set; }
    }
}
