//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucKhoaK22CNT3Lesson12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vdk_SACH
    {
        public string Vdk_MaSach { get; set; }
        public string Vdk_TenSach { get; set; }
        public Nullable<int> Vdk_SoTrang { get; set; }
        public Nullable<int> Vdk_NamXB { get; set; }
        public string Vdk_MaTG { get; set; }
        public Nullable<bool> Vdk_TrangThai { get; set; }
    }
}
