//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VdkBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vdkKhoa
    {
        public string VdkMaKH { get; set; }
        public string VdkTenKH { get; set; }
        public Nullable<bool> VdkTrangThai { get; set; }
    }
}
