//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VdkBaiKiemTraGK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VdkK22CNT3Lesson07DbEntities : DbContext
    {
        public VdkK22CNT3Lesson07DbEntities()
            : base("name=VdkK22CNT3Lesson07DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vdkKhoa> vdkKhoa { get; set; }
        public virtual DbSet<vdkSinhVien> vdkSinhVien { get; set; }
    }
}
