//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VdkBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vdkSinhVien
    {
        public string VdkMaSV { get; set; }
        public string VdkHoSV { get; set; }
        public string VdkTenSV { get; set; }
        public Nullable<System.DateTime> VdkNgaySinh { get; set; }
        public Nullable<bool> VdkPhai { get; set; }
        public string VdkPhone { get; set; }
        public string VdkEmail { get; set; }
        public string VdkMaKH { get; set; }
    }
}
